# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ei se toimi!
email: matti.lyra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  python, spark, AI and possibly other things as well
  <a href="http://stackoverflow.com/users/100190/matti-lyra">
    <img src="http://stackoverflow.com/users/flair/100190.png" width="208" height="58" alt="Matti Lyra at Stack Overflow, Q&amp;A for professional and enthusiast programmers" title="profile for Matti Lyra at Stack Overflow, Q&amp;A for professional and enthusiast programmers">
  </a>
baseurl: ""
url: "https://mattilyra.github.io"
twitter_username: mattilyra
github_username:  mattilyra

# Build settings
markdown: kramdown
