# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matti Lyra
email: matti.lyra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  python, spark, AI and possibly other things
baseurl: ""
url: "https://mattilyra.github.io"
twitter_username: mattilyra
github_username:  mattilyra

# Build settings
markdown: kramdown
